apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: operations.core.kops.aks.microsoft.com
spec:
  group: core.kops.aks.microsoft.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            status:
              type: object
            spec:
              type: object
  scope: Namespaced
  names:
    plural: operations
    singular: operation
    kind: Operation
    shortNames:
      - op
