apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: operations.yourgroup.yourdomain.com
spec:
  group: yourgroup.yourdomain.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                operationType:
                  type: string
  scope: Namespaced
  names:
    plural: operations
    singular: operation
    kind: Operation
    shortNames:
      - op
